name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
#  install:
#    name: Pretest Install
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16'
#          #cache: 'yarn'
#      - run: npm install --global yarn
#      - run: yarn install
  build:
    #needs: install
    name: Build
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: self-hosted
    steps:
      - run: echo ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          #cache: 'yarn'
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn build:linux