name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  install:
    name: Test Install
    runs-on: self-hosted
    steps:
      - run: doas update
      - run: doas apk add discover
      - run: doas apk add wine
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
  build:
    needs: install
    name: Build
    runs-on: self-hosted
    steps:
      - run: doas update
      - run: doas apk add discover
      - run: doas apk add wine
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build:nomac